server:
  port: 9001
spring:
  application:
    name: RabbitMq-Consumer
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue: "message_queue"
  exchange: "exchange_name"
  routing-key: "message_routing_key"

